//! Clean-room Kill Siri watchdog (inspired by term7 Kill-Siri process list).
//! We generate our own script + LaunchAgent; we do not download or vendor theirs.

use std::fs;
use std::path::PathBuf;
use std::process::Command;

use super::KillSiriStatus;

const LABEL: &str = "com.tor-socks-gui.kill-siri";

/// Same process names term7 watches — detected live with pgrep.
pub const SIRI_PROCS: &[&str] = &[
    "SiriAUSP",
    "siriinferenced",
    "siriactionsd",
    "siriknowledged",
    "sirittsd",
    "SiriTTSSynthesizerAU",
    "assistantd",
    "com.apple.siri.embeddedspeech",
    "com.apple.SiriTTSService.TrialProxy",
    "com.apple.siri-distributed-evaluation",
];

fn support_dir() -> Result<PathBuf, String> {
    let base = dirs::home_dir()
        .ok_or_else(|| "Could not resolve home directory".to_string())?
        .join("Library/Application Support/tor-socks-gui/kill-siri");
    fs::create_dir_all(&base).map_err(|e| format!("Failed to create kill-siri dir: {e}"))?;
    Ok(base)
}

fn script_path() -> Result<PathBuf, String> {
    Ok(support_dir()?.join("kill-siri.sh"))
}

fn agent_plist_path() -> Result<PathBuf, String> {
    let dir = dirs::home_dir()
        .ok_or_else(|| "Could not resolve home directory".to_string())?
        .join("Library/LaunchAgents");
    fs::create_dir_all(&dir).map_err(|e| format!("Failed to create LaunchAgents: {e}"))?;
    Ok(dir.join(format!("{LABEL}.plist")))
}

fn assistant_watch_path() -> PathBuf {
    dirs::home_dir()
        .unwrap_or_default()
        .join("Library/Assistant")
}

pub fn running_processes() -> Vec<String> {
    let mut out = Vec::new();
    for name in SIRI_PROCS {
        // Match term7: pgrep by name (not only exact -x; some Siri helpers are longer).
        let ok = Command::new("/usr/bin/pgrep")
            .arg(name)
            .stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::null())
            .status()
            .map(|s| s.success())
            .unwrap_or(false);
        if ok {
            out.push((*name).to_string());
        }
    }
    out
}

fn current_uid() -> String {
    Command::new("id")
        .arg("-u")
        .output()
        .ok()
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map(|s| s.trim().to_string())
        .unwrap_or_else(|| "501".into())
}

fn agent_loaded() -> bool {
    let uid = current_uid();
    Command::new("launchctl")
        .args(["print", &format!("gui/{uid}/{LABEL}")])
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

pub fn status() -> KillSiriStatus {
    let script_ok = script_path().map(|p| p.is_file()).unwrap_or(false);
    let plist_ok = agent_plist_path().map(|p| p.is_file()).unwrap_or(false);
    let installed = script_ok && plist_ok;
    let loaded = agent_loaded();
    let running = running_processes();
    let total = SIRI_PROCS.len();
    let mut detail = format!("{}/{} Siri-related processes running", running.len(), total);
    if installed && loaded {
        detail.push_str(" · killswitch installed");
    } else if installed {
        detail.push_str(" · files present, agent not loaded");
    } else {
        detail.push_str(" · killswitch not installed");
    }
    if installed && loaded && !running.is_empty() {
        detail.push_str(
            " · OS may have respawned some processes (watchdog clears on next Assistant activity)",
        );
    }
    KillSiriStatus {
        installed,
        agent_loaded: loaded,
        running,
        total_watched: total,
        detail,
    }
}

fn write_script() -> Result<PathBuf, String> {
    let path = script_path()?;
    let mut body = String::from(
        "#!/bin/bash\n# Generated by Tor SOCKS Manager — clean-room Kill Siri watchdog\nset -euo pipefail\nPROCS=(\n",
    );
    for p in SIRI_PROCS {
        body.push_str(&format!("  \"{p}\"\n"));
    }
    body.push_str(
        ")\nfor proc in \"${PROCS[@]}\"; do\n  if /usr/bin/pgrep \"$proc\" >/dev/null 2>&1; then\n    /usr/bin/pkill -9 \"$proc\" >/dev/null 2>&1 || true\n  fi\ndone\n",
    );
    fs::write(&path, body).map_err(|e| format!("Failed to write kill-siri.sh: {e}"))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(&path)
            .map_err(|e| e.to_string())?
            .permissions();
        perms.set_mode(0o755);
        fs::set_permissions(&path, perms).map_err(|e| e.to_string())?;
    }
    Ok(path)
}

fn write_plist(script: &PathBuf) -> Result<PathBuf, String> {
    let plist = agent_plist_path()?;
    let watch = assistant_watch_path();
    let content = format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>{LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>{script}</string>
  </array>
  <key>WatchPaths</key>
  <array>
    <string>{watch}</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
</dict>
</plist>
"#,
        script = script.display(),
        watch = watch.display(),
    );
    fs::write(&plist, content).map_err(|e| format!("Failed to write LaunchAgent: {e}"))?;
    Ok(plist)
}

pub fn install() -> Result<String, String> {
    let script = write_script()?;
    let plist = write_plist(&script)?;
    let _ = fs::create_dir_all(assistant_watch_path());
    let domain = format!("gui/{}", current_uid());
    // bootout if already loaded, then bootstrap
    let _ = Command::new("launchctl")
        .args(["bootout", &domain, &plist.to_string_lossy()])
        .status();
    let status = Command::new("launchctl")
        .args(["bootstrap", &domain, &plist.to_string_lossy()])
        .status()
        .map_err(|e| format!("launchctl bootstrap failed: {e}"))?;
    if !status.success() {
        return Err("Failed to load Kill Siri LaunchAgent".into());
    }
    // Run once immediately
    let _ = Command::new(&script).status();
    crate::logs::append("Hardening: Kill Siri killswitch installed");
    Ok("Kill Siri killswitch installed (LaunchAgent). SIP stays on — this is a watchdog, not a permanent disable. Re-apply after major OS updates if needed.".into())
}

pub fn uninstall() -> Result<String, String> {
    let domain = format!("gui/{}", current_uid());
    if let Ok(plist) = agent_plist_path() {
        let _ = Command::new("launchctl")
            .args(["bootout", &domain, &plist.to_string_lossy()])
            .status();
        let _ = fs::remove_file(plist);
    }
    if let Ok(script) = script_path() {
        let _ = fs::remove_file(script);
    }
    if let Ok(dir) = support_dir() {
        let _ = fs::remove_dir(dir);
    }
    crate::logs::append("Hardening: Kill Siri killswitch removed");
    Ok("Kill Siri killswitch uninstalled".into())
}
